<a href="https://colab.research.google.com/github/vasyl-d/vasyl-d/blob/main/RAG_HR_with_API_KEY.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
!pip install -q google-generativeai PyPDF2 gradio

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 232.6/232.6 kB 5.3 MB/s eta 0:00:00

In [ ]:
import google.generativeai as genai
import os
import pandas as pd
import numpy as np
from PyPDF2 import PdfReader

/usr/local/lib/python3.12/dist-packages/google/colab/_import_hooks/_hook_injector.py:55: FutureWarning:

All support for the `google.generativeai` package has ended. It will no longer be receiving
updates or bug fixes. Please switch to the `google.genai` package as soon as possible.
See README for more details:

https://github.com/google-gemini/deprecated-generative-ai-python/blob/main/README.md

  loader.exec_module(module)

In [ ]:
from google.colab import userdata
api_key = userdata.get('GOOGLE_API_KEY')
genai.configure(api_key=api_key)
print("google.generativeai library imported and configured.")

google.generativeai library imported and configured.

## Етап 1: зчитування даних

In [ ]:
df = pd.DataFrame(columns=['Title','Text'])
df

Empty DataFrame
Columns: [Title, Text]
Index: []

In [ ]:
for file_name in os.listdir('.'):
    if file_name.endswith('.pdf'):
        try:
            with open(file_name,'rb') as file:
                pdf_reader = PdfReader(file)
                text = ''
                for page_num in range(len(pdf_reader.pages)):
                    text+=pdf_reader.pages[page_num].extract_text()
                    text = text.replace('\n', ' ')
                new_row = pd.DataFrame({'Title':[file_name], 'Text':[text]})
                df = pd.concat([df,new_row],ignore_index=True)
        except Exception as e:
            print(f"Error processing file {file_name}: {e}")

In [ ]:
df

,Title,Text
0,Політика Онбордингу_Офбордингу.pdf,🚀 Політика Онбордингу (Onboarding Poli...
1,Відпустки та Sick Leaves.pdf,🌴 Політика відпусток та Sick Leaves ...
2,Політика відряджень (Travel Policy).pdf,✈ Політика відряджень (Travel Policy) ...
3,Медичне страхування та Бенефіти.pdf,🩺 Медичне страхування та Бенефіти Ми...

In [ ]:
print(df['Text'].iloc[1])

🌴   Політика   відпусток   та   Sick   Leaves   1.   Оплачувана   щорічна   відпустка   (Paid   Time   Off   -   PTO)   1.1.   Нарахування   та   ліміти   ●   Кількість   днів:   Кожен   співробітник   має   право   на   24   робочих   дні   оплачуваної   відпустки   на   рік.   ●   Період   нарахування:   Відпустка   нараховується   пропорційно   відпрацьованому   часу,   1.67   дня   за   кожен   повний   місяць   роботи.   ●   Початок   використання:   Співробітник   може   брати   першу   відпустку   після   проходження   випробувального   терміну   (зазвичай   3   місяці),   якщо   інше   не   узгоджено   з   менеджером.   1.2.   Правила   планування   ●   Попереднє   сповіщення:   Про   відпустку   тривалістю   понад   3   дні   необхідно   повідомити   за   2   тижні .   Для   тривалих   відпусток   (понад   10   днів)   —   за   1   місяць .   ●   Blackout   dates:   (Опціонально)   Періоди,   коли   відпустки   обмежені   через   високе   навантаження   (наприклад,   перед   релізом   продукту   або   в   кінці   фінансового   року).   ●   Перенесення   залишків   (Carry-over):   На   кінець   календарного   року   співробітник   може   перенести   не   більше   5   днів   на   наступний   рік.   Ці   дні   мають   бути   використані   до   кінця   першого   кварталу   (31   березня).     2.   Лікарняні   (Sick   Leaves)   2.1.   Короткотермінові   лікарняні   (Self-certified)   ●   Кількість:   Компанія   надає   10   робочих   днів   на   рік,   які   оплачуються   на   100%   без   надання   медичної   довідки.   ●   Процедура:   Якщо   ви   почуваєтесь   зле,   ви   повинні   повідомити   свого   лінійного   менеджера   та   команду   в   Slack/Email   до   10:00   ранку   в   день   відсутності.   2.2.   Довготривалі   лікарняні   ●   Медичне   підтвердження:   Якщо   хвороба   триває   понад   3   робочі   дні   поспіль,   необхідно   надати   медичне   підтвердження   (лікарняний   лист).  ●   Оплата:   Оплата   здійснюється   згідно   з   трудовим   законодавством   або   внутрішнім   регламентом   компанії   (наприклад,   перші   10   днів   —   100%,   далі   —   75%   від   ставки).     3.   Спеціальні   види   відсутності   3.1.   Відпустка   за   власний   рахунок   (Unpaid   Leave)   Співробітник   може   подати   запит   на   неоплачувану   відпустку   з   поважних   особистих   причин.   Рішення   приймається   індивідуально   менеджером   та   HR- відділом   залежно   від   ситуації   та   навантаження   команди.   3.2.   Соціальні   відпустки   (Paid)   Компанія   надає   додаткові   оплачувані   вихідні   у   наступних   випадках:   ●   Весілля   співробітника:   3   робочі   дні.   ●   Народження   дитини   (для   батька):   3-5   робочих   днів   (додатково   до   державної   відпустки).   ●   Втрата   близької   людини   (Bereavement   leave):   3-5   робочих   днів.   3.3.   Державні   свята   Компанія   дотримується   офіційного   календаря   державних   свят   країни,   де   зареєстрований   співробітник.   Якщо   робота   у   святковий   день   є   критичною,   вона   компенсується   подвійною   оплатою   або   додатковим   вихідним   (Day   off).     4.   Як   подати   запит?   1.   Узгодьте   дати   усно   або   в   месенджері   зі   своїм   Team   Lead   /   Manager .   2.   Після   отримання   попереднього   "OK",   створіть   заявку   в   нашій   системі   обліку   (наприклад,   BambooHR,   Hurma,   PeopleForce   або   через   Google   Form).   3.   Після   фінального   апруву   додайте   відпустку   в   загальний   календар   команди   та   встановіть   Auto-reply   (OOO)   у   пошті   та   статус   у   Slack.

## Етап 2: Векторизація

In [ ]:
texts = df['Text']
task_type = 'RETRIEVAL_DOCUMENT'
result = genai.embed_content(model="gemini-embedding-001", content=texts)
print(result)

{'embedding': [[0.005272668, 0.011680875, 0.03261762, -0.04466654, 0.009408942, 0.0022847487, 0.0070045525, 0.0084037, -0.024211675, -0.012853488, -0.013170113, -0.020980952, -0.0052836346, -0.0060728113, 0.12163957, 0.0030098504, -0.0040123593, 0.002314985, -0.025725396, -0.00710175, 0.016468631, -0.0139576895, -0.0048765196, -0.015636088, -0.025424413, -0.03514095, 0.0033694843, 0.028170565, 0.016306989, -0.013241446, -0.022169916, 0.024471836, 0.02057997, 0.03832741, -0.0039480124, 0.017969701, 0.007593964, -0.017584376, -0.009904694, 0.009094559, 0.009314851, -0.02621553, 0.008292955, -0.0015334872, -0.00034231177, -0.021075344, -0.010908862, -0.03948735, -0.011168691, 0.01307214, 0.002450139, 0.011759737, 0.016753653, -0.1816716, -0.019652499, -0.029140847, 0.0049014883, -0.0015234428, 0.0067341304, -0.03087031, -0.016303219, 0.028395709, -0.009142465, -0.006472891, -0.0065899356, -0.03668345, 0.01775724, 0.000831556, 0.013481925, -0.0109106405, 0.009988592, 0.016876921, 0.00090452685, -0.017549824, -0.023252722, -0.0247384, 0.005375679, -0.0016451473, -0.004761053, 0.013822974, -0.013155483, -0.012646851, 0.016831517, -0.011851666, 0.005314227, -0.019530399, 0.027889777, 0.01655045, -0.007823864, 0.030876817, 0.0038122595, 0.019486714, 0.0028080908, -0.022286441, 0.016853014, 0.005013067, 0.008467915, -0.0078033367, -0.0019122699, -0.009475913, -0.01035768, -0.009893675, -0.0035082283, -0.006995774, 0.009566752, -0.0030399556, 0.025203533, -0.028924432, 0.025380237, -0.018054333, 0.0037166274, 0.007861915, 0.016095717, -0.0028899657, 0.018352611, -0.14536612, -0.0020310394, -0.011287973, -0.0019810488, -0.01694473, -0.010211133, -0.026455665, 0.016484367, 0.013422224, -0.0024093883, -0.026963128, 0.02449544, -0.0059423526, 0.008472807, 0.013749817, -0.018617999, -0.025385961, 0.028553648, -0.010870552, 0.0051909867, 0.03051703, -0.0026747414, -0.022713222, -0.017246636, -0.014530128, 0.013983741, 0.0029619732, -0.00305798, -0.009412284, -0.0036040135, -0.017650865, -0.00928614, -0.01992924, -0.015651723, -0.018094074, -0.014330078, -0.0089535415, -0.026933085, -0.0011437607, -0.003129085, -0.021090629, 0.00040851044, 0.025902746, -0.020476164, 0.0052632964, 0.0071018967, 0.0115447575, -0.018679053, 0.019099828, 0.008674243, 0.003152041, 0.00203051, 0.018517466, -0.0066240584, 0.012541583, 0.0012348242, 0.015922626, -0.017662613, -0.019928338, 0.011905728, 0.004980326, -0.0098965075, 0.0073777847, 0.017296357, -0.018438004, 0.00018366329, 0.007314517, 0.002499583, 0.012749823, 0.0016171889, -0.01078373, 0.012176174, 0.01147199, 0.0037133698, 0.017385082, -0.0007376783, -0.013697454, -0.009100139, -0.0012173271, -0.004660155, -0.01433065, -0.018457102, 0.012836148, 0.015812352, 0.0162279, 0.030821964, 0.0021348607, -0.006858914, -0.026864242, 0.016992357, -0.0058857384, -0.021240773, -0.009701479, -0.0041986876, 0.01198354, -0.031119354, 0.02007935, 0.018943524, 0.0054585873, 0.0036172029, -0.048572313, -0.0083473595, 0.004239024, -0.028269311, 0.004624475, 0.006559997, 0.007212893, 0.0010884936, 0.03811993, 0.015025516, 0.00082658714, 0.04121006, -0.020042405, -0.0050699003, -0.021580206, 0.014395736, 0.0013896024, -0.018662626, 0.0138892, 0.02948665, -0.022723258, 0.010768451, 0.028369373, 0.019675786, 0.009451226, -0.010051841, 0.0013325824, -0.011955582, -0.00041162927, 0.019307157, 4.266139e-05, -0.010578739, -0.026497643, 0.02773301, 0.011015611, -0.011784932, 0.007657542, -0.0028585722, -0.020691555, -0.015447091, -0.008970452, 0.01281869, -0.002770056, -9.065844e-05, -0.0065493276, -0.0058092526, 0.0025197286, -0.019439762, -0.017081222, -0.0025540793, 0.020158025, 0.0014928438, 0.024785843, -0.009484011, 0.010051038, 0.013465186, -0.008182511, -0.0074773245, 0.0073632197, 0.0057602366, -0.013010234, -0.07747258, 0.03540371, -0.005675057, -0.008431753, -0.010447023, -0.001897545, -0.00028191006, 0.01132165, 0.013440191, 0.021047145, 0.004834903, 0.0106225405, 0.0067884517, -0.003407592, -0.00661679, -0.0067959656, 0.0075517185, -0.024132773, -0.00083978754, -0.03350616, -0.02470048, -0.02911823, 0.016881002, -0.029042553, 0.006981214, -0.014620385, 0.014627283, 0.057870675, 0.016061835, -0.015724106, 0.012370881, 0.048099525, -0.014885964, 0.0099609485, 0.029398514, 0.016337568, -0.010224297, -0.011609343, -0.0007797099, -0.0067664096, 0.011529753, -0.0068823025, -0.018127045, -0.02003053, -0.021676185, 0.028747432, -0.026281778, 0.010440926, -0.01326028, 0.004586682, -0.02146265, 0.027203707, 0.013933697, 0.012810588, 0.0052712895, 0.026401153, 0.0047239386, -0.025385126, -0.0039649033, 0.015110682, -0.003244854, 0.012391683, 0.023070619, 0.0077825203, 0.010057962, 0.012249334, -0.025928788, 0.0014762115, -0.004270327, 0.0015284158, -0.008830293, -0.0060552773, 0.007887716, -0.012408344, -0.0012873556, -0.000753103, 0.01832213, -0.001013109, -0.017597277, -0.0042383173, -0.018627126, -0.001791632, 0.011909675, 0.037825525, 0.009120696, -0.008025312, 0.01688832, -0.011137693, 0.009575101, -0.025716268, -0.029572237, 0.0134948725, -0.00081461365, 0.0016211037, 0.0013602703, 0.012512594, -0.014834633, -0.02464744, -0.01386995, 0.011556434, -0.030559005, 0.005097099, -0.0038391938, 0.0006767496, -0.008166778, 0.034338158, -0.00405809, 0.0052573425, 0.012331426, 0.0011778759, 0.018910537, 0.00056326506, 0.013635991, 0.029119732, -0.03316086, -0.0051307008, 0.0051879664, -0.000117012765, -0.008780281, 0.0047508893, -0.018882308, -0.019433498, 0.01173448, 0.008887523, 0.0017975898, 0.02574914, -0.024780173, 0.0069202995, 0.0045997384, -0.003658059, 0.019333534, -0.0054181833, -0.016797395, 0.002971203, 0.008568715, 0.013954768, -0.0011999146, -0.004934243, 0.025837418, -0.0038308874, -0.011694141, 0.02634286, 0.032432694, -0.01801592, 0.0025440475, 0.016468877, -0.02038543, 0.005128345, -0.0037490816, 0.003761319, -0.023845362, -0.005079631, -0.010942132, 0.02688452, -0.0038096702, 0.0031671443, -0.008501303, -0.031193081, -0.00990742, -0.017999506, 0.007857662, 0.010612094, -0.021463811, -0.00044346173, -0.0029334654, 0.011083186, -0.02584939, -0.014745155, 0.027293721, -0.0018160398, 0.01324404, -0.0034310513, -0.025551267, -0.0004915634, 0.03849632, 0.011159237, 0.0065559978, -0.036177676, -0.0041905944, -0.006908124, -0.016174788, -0.016532686, -0.006819734, -0.011143405, 0.006487558, 0.020668803, 0.0007871189, -0.023583282, -0.016223958, -0.0018524699, -0.013204877, -0.008677108, 0.002981977, -0.00021882352, 0.0027659123, -0.0044840905, 0.015158367, -0.016667869, 0.030586557, -0.025634024, 0.0023075065, -0.02131707, 0.03867602, 0.0059814802, -0.0041792165, -0.002179424, 0.007915961, 0.009029085, -0.008184644, -0.009278901, -0.003261584, 0.0067326687, 0.01648147, -0.0019303646, 0.0011839116, 0.032800183, -0.0053302045, 0.005816169, -0.032992497, 0.026713569, -0.012339559, 0.011884033, 0.0044028787, 0.005869577, -0.01418994, 0.02185877, 0.010687007, 0.0032845032, 0.0050744032, -0.007203012, 0.0055262484, -0.025019083, -0.017114392, -0.006437359, 0.015499406, 0.0015856583, -0.002361891, 0.032742996, -0.0135626085, -0.018508418, -0.0028028025, 0.009539852, 0.015667263, -0.019676479, -0.020262651, 0.004692604, -0.011878564, 0.012331991, 0.012969, 0.004496872, -0.0069626616, 0.016195064, 0.03795932, -0.00043122988, -0.015034332, 0.034047913, 0.0031459352, -0.03117258, 0.008023755, -0.013077685, 0.0053935125, 0.008559443, 0.025374124, -0.00017848863, -0.024123978, -0.0099258665, -0.017101757, -0.027476303, -0.005965006, -0.11119311, -0.027615685, -0.016694807, 0.02880814, 0.00010371935, 0.02328051, -0.012810064, -0.006266869, 0.014640348, -0.0067996066, -0.020194935, -0.014793298, 0.018853996, 0.006303291, -0.023350546, -0.017251031, -0.013863369, 0.0023817087, 0.007919953, -0.03080451, -0.0061462903, 0.02032461, 0.0025730098, -0.017151833, 0.02087184, -0.0067817247, 0.0013877887, -0.02077729, 0.0050985673, -0.01101341, -0.023532553, -0.0070537897, 0.011840944, 0.036484156, -0.0016914806, 0.0070953127, -0.003818899, 0.008905, 0.02196996, 0.005730812, 0.014880713, 0.0011647745, -0.020211464, -0.023548929, 0.010097252, 0.01685224, 0.018591387, -0.012367969, 0.015524951, 0.01896403, -0.024047716, -0.0028897622, -0.022704022, -0.00080372836, 0.028705304, 0.006815588, 0.00011675838, 0.017753573, -0.03219118, -0.011495074, -0.01848048, 0.0022619455, 0.019526066, 0.04094448, -0.001744228, 0.011490391, -0.0052048448, 0.007966495, -0.013323655, -0.0049189683, -0.05992854, -0.044643804, -0.016678583, 0.005768886, -0.007872592, 0.0021121637, 0.006520946, 0.02502397, -0.02305432, -0.0054451264, 0.0023165185, 0.0048689786, -0.06558558, -0.0021973674, 0.018127717, 0.008706952, 0.022091553, -0.01253521, 0.027973475, -0.015936058, 0.003760518, 0.0051722433, -0.009456996, 0.008525116, 0.035952955, -0.011818711, 0.015632087, -0.006348441, 0.0024676956, -0.01819132, 0.0010228682, -0.010799514, -0.018758062, -3.5175937e-05, 0.011203486, -0.0134307025, 0.016724285, -0.015192367, -0.010094791, -0.0064347954, -0.0006467772, 0.010765218, 0.0068086805, -0.16225149, 0.006412434, -0.023307841, 0.033411127, -0.017480327, 0.010927282, -0.007856548, -0.006705332, -0.005645486, -0.016745009, -0.002393538, -0.062205702, -0.05118431, 0.0018023493, -0.010420684, 0.09074826, -0.00047582568, 0.0077069965, -0.013913513, -0.010140355, 0.026361048, -0.01619556, -0.008273978, -0.009628292, -0.017131297, -0.028993012, 0.00845273, 0.010965039, 0.021044113, 0.008155722, 0.017463949, 0.01513059, 0.0009467981, 0.015647518, -0.007311775, -0.014759317, -0.008030431, -0.014163882, 0.005649272, 0.008347813, -0.0018070511, 0.01684722, 0.007534587, -0.010718864, 0.026054394, -0.002130297, -0.0062880134, -0.0161044, 0.011653678, -0.012652902, -0.028494202, -0.07172713, 0.0014412759, -0.008093458, 0.0071572606, -0.00905808, -0.0017749781, -0.029813936, 0.015112509, 0.000860308, 0.009749476, 0.026965346, 0.0253463, 0.010040722, -0.007487399, -0.011100692, 0.050564945, 0.028461514, -0.012789562, 0.028249312, 0.014515233, 0.005278887, 0.013809319, 0.005481888, -0.001259593, -0.014190554, -0.00994061, -0.0010511149, 0.0067549283, -0.007561524, 0.009708382, 0.026689867, 0.011268892, -0.016311992, -0.019041272, 0.0059565916, -0.0076571936, 0.012152866, -0.021577949, -0.024028137, -0.008709724, 0.015369545, 0.033896137, -0.016971182, -0.017828163, 0.012088259, -0.023543842, 0.02241482, -0.018008515, 0.007696839, 0.034320462, 9.4320814e-05, -0.013110442, -0.028420117, -0.00668008, -0.013768695, 0.036674008, -0.015454533, 0.009176369, -0.00013145444, 0.0038532773, -0.007716614, 0.00492899, 0.015206321, -0.0005316874, -0.0035209523, 0.014277712, -0.008235649, 0.0060973084, -0.0016756335, -0.016029363, 0.001395085, -0.0092706885, 0.020442497, 0.011762082, -0.013301821, 0.0009406596, 0.0011244069, -0.00025449813, -0.02013605, 0.019092876, -0.006626689, -0.0019796654, 0.00027850352, 0.0052576386, -0.0039524282, 0.002074211, 0.005506763, -0.00044167627, -0.01667009, 0.017449124, -0.011096826, 0.01434025, 0.0073002693, -0.00525154, 0.009122347, 0.0007255509, -0.0080188485, 0.0064059403, -0.011861244, -0.011987137, -0.0154792685, 0.008506389, 0.0019267234, -0.006332189, 0.009334213, 0.019581262, 0.0031301975, -0.016212683, -0.0037803967, 8.0588456e-05, 0.009720196, 0.0016296679, 0.004440833, 0.0015480447, -0.016948733, -0.0071076485, -0.0059759016, 0.006825083, 0.015496377, 0.0057504233, -0.00039374738, -0.01230808, -0.016747499, 0.011969288, -0.004851412, -0.022512555, -0.0045355256, -0.011028823, -0.019170636, -0.0076473188, -0.016321214, 0.01573726, -0.002353978, -0.00921328, 0.0010304765, 0.009209212, 0.011060086, -0.0028301498, -0.0054635997, 0.02083529, -0.012864937, 0.009561269, -0.0057111806, -0.0001787646, 0.013813237, -0.007666244, -0.015040841, -0.013514423, 0.013443921, -2.9083438e-05, -0.0022380124, -0.00021484919, 0.0026238502, -0.006189102, -0.0058940644, -0.0040701106, 0.022256877, -0.008346952, -0.0012693623, 0.011496488, 0.0072647366, 0.010768443, -0.001318812, 0.0011220226, -0.010573387, 0.0115518365, 0.004115987, -0.028894695, 0.020355117, -0.0107091, 0.013945604, 0.0058103884, 0.0034153757, -0.013529268, -0.008071256, -0.01093477, 0.0065226676, -0.005644492, 0.007987375, 0.016002364, -0.011070145, 0.005209003, -0.0019636054, -0.01866547, 0.028067935, -0.0062554916, -0.005349558, -0.006030919, 0.01609731, -0.010831347, 0.012076234, 0.014031343, 0.0070073833, 0.009360543, 0.004953702, -0.011679897, 0.002353645, -0.017094722, -0.002298452, 0.0014897604, 0.013956184, 0.023623608, 0.006371222, -0.00510847, -0.011724707, 0.0043957946, -0.0053928765, -0.0038327447, -0.0037614913, 0.010486073, 0.012300524, 0.0058947555, -0.0063960464, 0.003979004, -0.003821351, 0.0035186005, -0.0027740917, -0.020232866, 0.025453331, 0.01369841, -0.0002682142, 0.008087687, -0.0039841686, 0.005736206, -0.008010962, -0.017652847, 0.00999178, 0.004252689, 0.0019449432, 0.011824258, 0.010344349, -0.0033114026, 0.0027863127, 0.014998874, 0.024213238, 0.0067582885, -0.01251163, -0.0038291037, -0.01824802, -0.01829554, 0.004201883, -0.020385504, 0.0032146228, -0.003941555, 0.008060771, -0.0050072973, -0.0055793137, -0.01906458, -0.004470597, -0.0061314483, 0.0061832224, -0.0018704138, -0.011189447, 0.011121725, -0.011507398, 0.008179201, -0.01359181, 0.010270158, 0.010838794, 0.108813606, -0.020914355, -0.008274819, -0.008181791, -0.0028209807, 0.0037268994, -0.0033542276, -0.0074953362, 0.01634451, -0.014104319, -0.0006935868, -0.0064392393, 0.013483157, -0.012188274, 0.0054007466, 0.01249533, 0.0044715186, 0.02274013, 0.004442057, 0.007598805, -0.007011032, 0.0039704596, -0.0059029344, -0.01246022, 0.0013169025, 0.01511906, -0.0016932371, -0.00033012984, -0.011515093, 0.0072060158, -0.0028120838, -0.0022123603, 0.0016167508, 0.012648872, -0.022621427, 0.0027442616, -0.007027306, 0.040101446, 0.0069708694, -0.00010314663, 0.013536513, -0.0049216785, -0.0077514695, 0.022020595, 0.020783214, 0.0063086157, -0.0196824, 0.0034873004, 0.012970484, 0.020817464, -0.008701319, -0.005420184, 0.0085836, -0.010529424, -0.011667984, -0.0034266084, 0.0053747045, 0.0058875503, 0.0041373344, -5.1930634e-05, 0.0047182753, 0.02728665, -0.009971397, 0.008387286, 0.005625337, -0.025750875, -0.008407635, 0.005779635, -0.015644588, -0.017959837, -0.00093660894, -0.0059012724, -0.018181495, -0.0033434648, 0.019605013, 0.0015669961, 0.009886794, 0.009995807, -0.0008278543, -0.028720563, -0.0012735784, 2.3441089e-05, -0.01062601, 0.008379541, -0.0015214612, -0.0055332747, -0.0070934403, -0.00060862146, 0.02078942, 0.0064525553, 0.009870991, -0.00013142357, -0.003112285, 0.006960667, -0.0069776443, -0.006353742, 0.048985124, 0.022229394, 0.0020481911, 0.0025878472, 0.010559392, -0.020480802, -0.005852886, -0.011287413, 0.00064725825, -0.00603929, 0.018150775, -0.0008292421, -0.0083348425, -0.0045380737, -0.017026605, 0.002606882, 0.0058194124, 0.006619496, -0.021669615, -0.030633084, -0.0060475697, 0.011555104, 0.0073636803, -0.0024629708, 0.017419899, 0.00822306, -0.017068356, 0.014491975, -0.0040609622, 0.0010485862, 0.015081108, -0.013831337, -0.0037593162, 0.00642672, -0.0014539988, 0.009070959, -0.02439166, 0.01683159, -0.008518713, 0.002486453, 0.009195376, 0.00010449989, 0.020904344, -0.0017218936, -0.0073614838, 0.0007642071, -0.003188146, 0.0094725685, -0.016739603, -0.008743882, 0.014079124, 0.005561303, -0.00022093293, -0.01108631, -0.023708196, -0.007033278, 0.001734533, 0.03486085, -0.002036109, -0.0060884296, 0.0012405657, 0.01779748, 0.017521663, -0.012594627, -0.0011964155, -0.011570083, -0.01019783, -0.0034622506, 0.004613631, -0.015188658, 0.018706964, 0.012864289, -0.003762119, 0.0029768231, 0.0013675981, -0.0026034913, 0.0042949095, 0.010871661, -0.0136412075, 4.1787167e-05, 0.0063394997, 0.0008757451, 0.0034640091, 0.023948975, -0.0004365469, -0.0043057622, -0.01456957, -0.018479085, -0.013150577, -0.0044398396, -0.009070105, -0.0130057745, 0.02223789, -0.01494952, 0.009507944, -0.024255065, 0.012944835, -0.010642314, 0.006109845, 0.004504369, 0.005953853, 0.014099641, 0.025324667, -0.006602372, 0.009921052, 0.0042471495, 0.007022958, -0.011089475, 0.002216266, 0.0068774438, -0.007276129, 0.008886808, -0.0036309473, -0.008535068, -0.0041903243, -0.025768803, 0.002134111, 0.0014105838, 0.0032357734, -0.0014272134, 0.011798383, -0.014881311, -0.016250886, -0.026693972, 0.004307152, -0.0015694808, 0.011026147, -0.018810024, 0.0071239504, -0.010738071, 0.0132130515, 0.0068262285, 0.009747841, -0.0081426, -0.0017391536, -0.0033782062, -0.0052649914, -0.009997463, -0.015021934, -0.003686603, 0.005519439, 0.011117988, 0.019735139, -0.020108217, -0.009389129, -0.0052467897, -0.009509783, 0.0060023656, 0.00024565437, 0.0036544173, -0.024672702, 2.4406467e-05, -0.02322651, -0.0035820315, -0.0025604905, -0.005317863, -0.0040868255, -0.010634936, 0.009138613, -0.0062110173, -0.0034267916, -0.07395892, 0.0063518, 0.011621932, 0.005721578, 0.0018073019, -0.014379611, -0.02073384, -0.0015996096, 0.008201852, -0.008759303, 0.0038643081, -0.008464195, -0.0044734366, 0.007513959, -0.004397051, 0.004067635, -0.012281556, 0.0150062395, 0.0020341028, -0.009534266, -0.017806387, -0.008164217, -0.0031053955, -0.0128218755, -0.007871203, -0.008052797, 0.0003441274, 0.0006940507, 0.0022362561, 0.002647188, 0.012575579, -0.017896766, -0.0046361517, -0.0030249436, 0.005293004, 0.010485339, -0.0028734182, -0.0031815683, 0.016658137, 0.0011841567, 0.0252535, -0.008254083, -0.0015897873, 0.0038236508, 0.012611646, -0.0010006418, 0.00073937175, 0.0018447088, 0.0023391938, 0.009504399, 0.0054556797, 0.010300601, -0.0048193564, 0.024518225, 0.012189084, -0.025815384, 0.006708932, 0.005963363, -0.00110706, -0.002287251, 0.00057652424, 0.021413172, 0.0055792923, -0.0034469077, 0.006248319, -0.006822528, 0.010335451, -0.001488354, -0.007853731, -0.0014373888, 0.004982822, -0.008211345, 0.009575401, -0.020254906, -0.013588853, 0.0030243825, 0.016264424, 0.006468408, -0.0007324734, -0.0007180782, 0.009625549, 0.016635174, 0.0019989724, -0.0009408258, -0.0019726749, 0.013318879, 0.0030436832, -0.005284807, -0.012364606, -0.0103289895, -0.009731246, -0.002398201, 0.0052658278, 0.004732879, -0.011121415, -0.0094813015, -0.029350005, -0.0055312905, -0.007244785, 0.007931169, -0.029064097, 0.0012324562, -0.003951481, 0.0006548486, -0.0130375875, -0.0045213164, 0.0015122737, -0.016291657, 0.0066262307, -0.0050321566, 0.0055250293, 0.0048365775, 0.00013866503, 0.00019886895, -0.0041401903, -0.018996086, 0.00238082, -0.01928341, -0.001297326, -0.008911822, -0.008146457, 0.027545707, -0.006182558, 0.013624976, 0.02296248, 0.0135336, -0.0042758225, -0.0005324491, 0.010478716, -0.01770749, 0.0106557105, 0.0050095352, -0.006026052, -0.018794907, 0.007461543, 0.003354862, 0.009247175, -0.0047753174, 0.0020871924, 0.0008255581, 0.015362993, -0.014844835, 0.00050245685, 0.002148542, -0.015071151, 0.016265053, -0.0022301464, -0.0038964318, 0.0041805804, 0.009737394, 0.011951562, 0.0014801195, 0.006256956, 0.012841568, -0.00133563, 0.0021663536, -0.00983234, 0.0028135006, 0.008049154, -0.017674685, 0.0345473, -0.008542781, 0.016666798, -0.0017108986, -0.004928735, -0.001821239, -0.016229877, -0.007896547, -0.0063523245, -0.003497378, -0.0034359992, 0.009510356, 0.003069736, 0.008194425, -2.1057378e-05, 0.018475827, 0.010116706, -0.0024118156, -0.008483967, 0.0032815405, -0.00018031785, -0.0066303657, 0.006713607, 0.0074971444, 0.0039293696, -0.0058295256, -0.009714898, 0.0015745217, -0.0033145614, -0.0018640084, 0.0025920267, -0.009980614, 0.0059239073, 7.379408e-05, 0.0042645643, 0.012387179, 0.003225773, -0.004676769, 0.0116976965, -0.0036261103, -0.011236806, -0.0034208503, 0.0148291085, -0.013687802, 0.016700428, -0.100046985, 0.013339687, 0.00044227843, -0.0060780174, 0.003660116, -0.0072744447, 0.010466027, -0.008026613, -0.011572751, 0.01559893, -0.011170094, 0.012797739, 0.011654821, -0.029191488, 0.00036970986, 0.0030745722, -0.0027209457, 0.017918367, -0.0048025195, 0.0030944857, 0.0049384506, 0.015710149, -0.022418736, 0.0010696696, 0.

In [ ]:
print(result['embedding'])

[[0.005272668, 0.011680875, 0.03261762, -0.04466654, 0.009408942, 0.0022847487, 0.0070045525, 0.0084037, -0.024211675, -0.012853488, -0.013170113, -0.020980952, -0.0052836346, -0.0060728113, 0.12163957, 0.0030098504, -0.0040123593, 0.002314985, -0.025725396, -0.00710175, 0.016468631, -0.0139576895, -0.0048765196, -0.015636088, -0.025424413, -0.03514095, 0.0033694843, 0.028170565, 0.016306989, -0.013241446, -0.022169916, 0.024471836, 0.02057997, 0.03832741, -0.0039480124, 0.017969701, 0.007593964, -0.017584376, -0.009904694, 0.009094559, 0.009314851, -0.02621553, 0.008292955, -0.0015334872, -0.00034231177, -0.021075344, -0.010908862, -0.03948735, -0.011168691, 0.01307214, 0.002450139, 0.011759737, 0.016753653, -0.1816716, -0.019652499, -0.029140847, 0.0049014883, -0.0015234428, 0.0067341304, -0.03087031, -0.016303219, 0.028395709, -0.009142465, -0.006472891, -0.0065899356, -0.03668345, 0.01775724, 0.000831556, 0.013481925, -0.0109106405, 0.009988592, 0.016876921, 0.00090452685, -0.017549824, -0.023252722, -0.0247384, 0.005375679, -0.0016451473, -0.004761053, 0.013822974, -0.013155483, -0.012646851, 0.016831517, -0.011851666, 0.005314227, -0.019530399, 0.027889777, 0.01655045, -0.007823864, 0.030876817, 0.0038122595, 0.019486714, 0.0028080908, -0.022286441, 0.016853014, 0.005013067, 0.008467915, -0.0078033367, -0.0019122699, -0.009475913, -0.01035768, -0.009893675, -0.0035082283, -0.006995774, 0.009566752, -0.0030399556, 0.025203533, -0.028924432, 0.025380237, -0.018054333, 0.0037166274, 0.007861915, 0.016095717, -0.0028899657, 0.018352611, -0.14536612, -0.0020310394, -0.011287973, -0.0019810488, -0.01694473, -0.010211133, -0.026455665, 0.016484367, 0.013422224, -0.0024093883, -0.026963128, 0.02449544, -0.0059423526, 0.008472807, 0.013749817, -0.018617999, -0.025385961, 0.028553648, -0.010870552, 0.0051909867, 0.03051703, -0.0026747414, -0.022713222, -0.017246636, -0.014530128, 0.013983741, 0.0029619732, -0.00305798, -0.009412284, -0.0036040135, -0.017650865, -0.00928614, -0.01992924, -0.015651723, -0.018094074, -0.014330078, -0.0089535415, -0.026933085, -0.0011437607, -0.003129085, -0.021090629, 0.00040851044, 0.025902746, -0.020476164, 0.0052632964, 0.0071018967, 0.0115447575, -0.018679053, 0.019099828, 0.008674243, 0.003152041, 0.00203051, 0.018517466, -0.0066240584, 0.012541583, 0.0012348242, 0.015922626, -0.017662613, -0.019928338, 0.011905728, 0.004980326, -0.0098965075, 0.0073777847, 0.017296357, -0.018438004, 0.00018366329, 0.007314517, 0.002499583, 0.012749823, 0.0016171889, -0.01078373, 0.012176174, 0.01147199, 0.0037133698, 0.017385082, -0.0007376783, -0.013697454, -0.009100139, -0.0012173271, -0.004660155, -0.01433065, -0.018457102, 0.012836148, 0.015812352, 0.0162279, 0.030821964, 0.0021348607, -0.006858914, -0.026864242, 0.016992357, -0.0058857384, -0.021240773, -0.009701479, -0.0041986876, 0.01198354, -0.031119354, 0.02007935, 0.018943524, 0.0054585873, 0.0036172029, -0.048572313, -0.0083473595, 0.004239024, -0.028269311, 0.004624475, 0.006559997, 0.007212893, 0.0010884936, 0.03811993, 0.015025516, 0.00082658714, 0.04121006, -0.020042405, -0.0050699003, -0.021580206, 0.014395736, 0.0013896024, -0.018662626, 0.0138892, 0.02948665, -0.022723258, 0.010768451, 0.028369373, 0.019675786, 0.009451226, -0.010051841, 0.0013325824, -0.011955582, -0.00041162927, 0.019307157, 4.266139e-05, -0.010578739, -0.026497643, 0.02773301, 0.011015611, -0.011784932, 0.007657542, -0.0028585722, -0.020691555, -0.015447091, -0.008970452, 0.01281869, -0.002770056, -9.065844e-05, -0.0065493276, -0.0058092526, 0.0025197286, -0.019439762, -0.017081222, -0.0025540793, 0.020158025, 0.0014928438, 0.024785843, -0.009484011, 0.010051038, 0.013465186, -0.008182511, -0.0074773245, 0.0073632197, 0.0057602366, -0.013010234, -0.07747258, 0.03540371, -0.005675057, -0.008431753, -0.010447023, -0.001897545, -0.00028191006, 0.01132165, 0.013440191, 0.021047145, 0.004834903, 0.0106225405, 0.0067884517, -0.003407592, -0.00661679, -0.0067959656, 0.0075517185, -0.024132773, -0.00083978754, -0.03350616, -0.02470048, -0.02911823, 0.016881002, -0.029042553, 0.006981214, -0.014620385, 0.014627283, 0.057870675, 0.016061835, -0.015724106, 0.012370881, 0.048099525, -0.014885964, 0.0099609485, 0.029398514, 0.016337568, -0.010224297, -0.011609343, -0.0007797099, -0.0067664096, 0.011529753, -0.0068823025, -0.018127045, -0.02003053, -0.021676185, 0.028747432, -0.026281778, 0.010440926, -0.01326028, 0.004586682, -0.02146265, 0.027203707, 0.013933697, 0.012810588, 0.0052712895, 0.026401153, 0.0047239386, -0.025385126, -0.0039649033, 0.015110682, -0.003244854, 0.012391683, 0.023070619, 0.0077825203, 0.010057962, 0.012249334, -0.025928788, 0.0014762115, -0.004270327, 0.0015284158, -0.008830293, -0.0060552773, 0.007887716, -0.012408344, -0.0012873556, -0.000753103, 0.01832213, -0.001013109, -0.017597277, -0.0042383173, -0.018627126, -0.001791632, 0.011909675, 0.037825525, 0.009120696, -0.008025312, 0.01688832, -0.011137693, 0.009575101, -0.025716268, -0.029572237, 0.0134948725, -0.00081461365, 0.0016211037, 0.0013602703, 0.012512594, -0.014834633, -0.02464744, -0.01386995, 0.011556434, -0.030559005, 0.005097099, -0.0038391938, 0.0006767496, -0.008166778, 0.034338158, -0.00405809, 0.0052573425, 0.012331426, 0.0011778759, 0.018910537, 0.00056326506, 0.013635991, 0.029119732, -0.03316086, -0.0051307008, 0.0051879664, -0.000117012765, -0.008780281, 0.0047508893, -0.018882308, -0.019433498, 0.01173448, 0.008887523, 0.0017975898, 0.02574914, -0.024780173, 0.0069202995, 0.0045997384, -0.003658059, 0.019333534, -0.0054181833, -0.016797395, 0.002971203, 0.008568715, 0.013954768, -0.0011999146, -0.004934243, 0.025837418, -0.0038308874, -0.011694141, 0.02634286, 0.032432694, -0.01801592, 0.0025440475, 0.016468877, -0.02038543, 0.005128345, -0.0037490816, 0.003761319, -0.023845362, -0.005079631, -0.010942132, 0.02688452, -0.0038096702, 0.0031671443, -0.008501303, -0.031193081, -0.00990742, -0.017999506, 0.007857662, 0.010612094, -0.021463811, -0.00044346173, -0.0029334654, 0.011083186, -0.02584939, -0.014745155, 0.027293721, -0.0018160398, 0.01324404, -0.0034310513, -0.025551267, -0.0004915634, 0.03849632, 0.011159237, 0.0065559978, -0.036177676, -0.0041905944, -0.006908124, -0.016174788, -0.016532686, -0.006819734, -0.011143405, 0.006487558, 0.020668803, 0.0007871189, -0.023583282, -0.016223958, -0.0018524699, -0.013204877, -0.008677108, 0.002981977, -0.00021882352, 0.0027659123, -0.0044840905, 0.015158367, -0.016667869, 0.030586557, -0.025634024, 0.0023075065, -0.02131707, 0.03867602, 0.0059814802, -0.0041792165, -0.002179424, 0.007915961, 0.009029085, -0.008184644, -0.009278901, -0.003261584, 0.0067326687, 0.01648147, -0.0019303646, 0.0011839116, 0.032800183, -0.0053302045, 0.005816169, -0.032992497, 0.026713569, -0.012339559, 0.011884033, 0.0044028787, 0.005869577, -0.01418994, 0.02185877, 0.010687007, 0.0032845032, 0.0050744032, -0.007203012, 0.0055262484, -0.025019083, -0.017114392, -0.006437359, 0.015499406, 0.0015856583, -0.002361891, 0.032742996, -0.0135626085, -0.018508418, -0.0028028025, 0.009539852, 0.015667263, -0.019676479, -0.020262651, 0.004692604, -0.011878564, 0.012331991, 0.012969, 0.004496872, -0.0069626616, 0.016195064, 0.03795932, -0.00043122988, -0.015034332, 0.034047913, 0.0031459352, -0.03117258, 0.008023755, -0.013077685, 0.0053935125, 0.008559443, 0.025374124, -0.00017848863, -0.024123978, -0.0099258665, -0.017101757, -0.027476303, -0.005965006, -0.11119311, -0.027615685, -0.016694807, 0.02880814, 0.00010371935, 0.02328051, -0.012810064, -0.006266869, 0.014640348, -0.0067996066, -0.020194935, -0.014793298, 0.018853996, 0.006303291, -0.023350546, -0.017251031, -0.013863369, 0.0023817087, 0.007919953, -0.03080451, -0.0061462903, 0.02032461, 0.0025730098, -0.017151833, 0.02087184, -0.0067817247, 0.0013877887, -0.02077729, 0.0050985673, -0.01101341, -0.023532553, -0.0070537897, 0.011840944, 0.036484156, -0.0016914806, 0.0070953127, -0.003818899, 0.008905, 0.02196996, 0.005730812, 0.014880713, 0.0011647745, -0.020211464, -0.023548929, 0.010097252, 0.01685224, 0.018591387, -0.012367969, 0.015524951, 0.01896403, -0.024047716, -0.0028897622, -0.022704022, -0.00080372836, 0.028705304, 0.006815588, 0.00011675838, 0.017753573, -0.03219118, -0.011495074, -0.01848048, 0.0022619455, 0.019526066, 0.04094448, -0.001744228, 0.011490391, -0.0052048448, 0.007966495, -0.013323655, -0.0049189683, -0.05992854, -0.044643804, -0.016678583, 0.005768886, -0.007872592, 0.0021121637, 0.006520946, 0.02502397, -0.02305432, -0.0054451264, 0.0023165185, 0.0048689786, -0.06558558, -0.0021973674, 0.018127717, 0.008706952, 0.022091553, -0.01253521, 0.027973475, -0.015936058, 0.003760518, 0.0051722433, -0.009456996, 0.008525116, 0.035952955, -0.011818711, 0.015632087, -0.006348441, 0.0024676956, -0.01819132, 0.0010228682, -0.010799514, -0.018758062, -3.5175937e-05, 0.011203486, -0.0134307025, 0.016724285, -0.015192367, -0.010094791, -0.0064347954, -0.0006467772, 0.010765218, 0.0068086805, -0.16225149, 0.006412434, -0.023307841, 0.033411127, -0.017480327, 0.010927282, -0.007856548, -0.006705332, -0.005645486, -0.016745009, -0.002393538, -0.062205702, -0.05118431, 0.0018023493, -0.010420684, 0.09074826, -0.00047582568, 0.0077069965, -0.013913513, -0.010140355, 0.026361048, -0.01619556, -0.008273978, -0.009628292, -0.017131297, -0.028993012, 0.00845273, 0.010965039, 0.021044113, 0.008155722, 0.017463949, 0.01513059, 0.0009467981, 0.015647518, -0.007311775, -0.014759317, -0.008030431, -0.014163882, 0.005649272, 0.008347813, -0.0018070511, 0.01684722, 0.007534587, -0.010718864, 0.026054394, -0.002130297, -0.0062880134, -0.0161044, 0.011653678, -0.012652902, -0.028494202, -0.07172713, 0.0014412759, -0.008093458, 0.0071572606, -0.00905808, -0.0017749781, -0.029813936, 0.015112509, 0.000860308, 0.009749476, 0.026965346, 0.0253463, 0.010040722, -0.007487399, -0.011100692, 0.050564945, 0.028461514, -0.012789562, 0.028249312, 0.014515233, 0.005278887, 0.013809319, 0.005481888, -0.001259593, -0.014190554, -0.00994061, -0.0010511149, 0.0067549283, -0.007561524, 0.009708382, 0.026689867, 0.011268892, -0.016311992, -0.019041272, 0.0059565916, -0.0076571936, 0.012152866, -0.021577949, -0.024028137, -0.008709724, 0.015369545, 0.033896137, -0.016971182, -0.017828163, 0.012088259, -0.023543842, 0.02241482, -0.018008515, 0.007696839, 0.034320462, 9.4320814e-05, -0.013110442, -0.028420117, -0.00668008, -0.013768695, 0.036674008, -0.015454533, 0.009176369, -0.00013145444, 0.0038532773, -0.007716614, 0.00492899, 0.015206321, -0.0005316874, -0.0035209523, 0.014277712, -0.008235649, 0.0060973084, -0.0016756335, -0.016029363, 0.001395085, -0.0092706885, 0.020442497, 0.011762082, -0.013301821, 0.0009406596, 0.0011244069, -0.00025449813, -0.02013605, 0.019092876, -0.006626689, -0.0019796654, 0.00027850352, 0.0052576386, -0.0039524282, 0.002074211, 0.005506763, -0.00044167627, -0.01667009, 0.017449124, -0.011096826, 0.01434025, 0.0073002693, -0.00525154, 0.009122347, 0.0007255509, -0.0080188485, 0.0064059403, -0.011861244, -0.011987137, -0.0154792685, 0.008506389, 0.0019267234, -0.006332189, 0.009334213, 0.019581262, 0.0031301975, -0.016212683, -0.0037803967, 8.0588456e-05, 0.009720196, 0.0016296679, 0.004440833, 0.0015480447, -0.016948733, -0.0071076485, -0.0059759016, 0.006825083, 0.015496377, 0.0057504233, -0.00039374738, -0.01230808, -0.016747499, 0.011969288, -0.004851412, -0.022512555, -0.0045355256, -0.011028823, -0.019170636, -0.0076473188, -0.016321214, 0.01573726, -0.002353978, -0.00921328, 0.0010304765, 0.009209212, 0.011060086, -0.0028301498, -0.0054635997, 0.02083529, -0.012864937, 0.009561269, -0.0057111806, -0.0001787646, 0.013813237, -0.007666244, -0.015040841, -0.013514423, 0.013443921, -2.9083438e-05, -0.0022380124, -0.00021484919, 0.0026238502, -0.006189102, -0.0058940644, -0.0040701106, 0.022256877, -0.008346952, -0.0012693623, 0.011496488, 0.0072647366, 0.010768443, -0.001318812, 0.0011220226, -0.010573387, 0.0115518365, 0.004115987, -0.028894695, 0.020355117, -0.0107091, 0.013945604, 0.0058103884, 0.0034153757, -0.013529268, -0.008071256, -0.01093477, 0.0065226676, -0.005644492, 0.007987375, 0.016002364, -0.011070145, 0.005209003, -0.0019636054, -0.01866547, 0.028067935, -0.0062554916, -0.005349558, -0.006030919, 0.01609731, -0.010831347, 0.012076234, 0.014031343, 0.0070073833, 0.009360543, 0.004953702, -0.011679897, 0.002353645, -0.017094722, -0.002298452, 0.0014897604, 0.013956184, 0.023623608, 0.006371222, -0.00510847, -0.011724707, 0.0043957946, -0.0053928765, -0.0038327447, -0.0037614913, 0.010486073, 0.012300524, 0.0058947555, -0.0063960464, 0.003979004, -0.003821351, 0.0035186005, -0.0027740917, -0.020232866, 0.025453331, 0.01369841, -0.0002682142, 0.008087687, -0.0039841686, 0.005736206, -0.008010962, -0.017652847, 0.00999178, 0.004252689, 0.0019449432, 0.011824258, 0.010344349, -0.0033114026, 0.0027863127, 0.014998874, 0.024213238, 0.0067582885, -0.01251163, -0.0038291037, -0.01824802, -0.01829554, 0.004201883, -0.020385504, 0.0032146228, -0.003941555, 0.008060771, -0.0050072973, -0.0055793137, -0.01906458, -0.004470597, -0.0061314483, 0.0061832224, -0.0018704138, -0.011189447, 0.011121725, -0.011507398, 0.008179201, -0.01359181, 0.010270158, 0.010838794, 0.108813606, -0.020914355, -0.008274819, -0.008181791, -0.0028209807, 0.0037268994, -0.0033542276, -0.0074953362, 0.01634451, -0.014104319, -0.0006935868, -0.0064392393, 0.013483157, -0.012188274, 0.0054007466, 0.01249533, 0.0044715186, 0.02274013, 0.004442057, 0.007598805, -0.007011032, 0.0039704596, -0.0059029344, -0.01246022, 0.0013169025, 0.01511906, -0.0016932371, -0.00033012984, -0.011515093, 0.0072060158, -0.0028120838, -0.0022123603, 0.0016167508, 0.012648872, -0.022621427, 0.0027442616, -0.007027306, 0.040101446, 0.0069708694, -0.00010314663, 0.013536513, -0.0049216785, -0.0077514695, 0.022020595, 0.020783214, 0.0063086157, -0.0196824, 0.0034873004, 0.012970484, 0.020817464, -0.008701319, -0.005420184, 0.0085836, -0.010529424, -0.011667984, -0.0034266084, 0.0053747045, 0.0058875503, 0.0041373344, -5.1930634e-05, 0.0047182753, 0.02728665, -0.009971397, 0.008387286, 0.005625337, -0.025750875, -0.008407635, 0.005779635, -0.015644588, -0.017959837, -0.00093660894, -0.0059012724, -0.018181495, -0.0033434648, 0.019605013, 0.0015669961, 0.009886794, 0.009995807, -0.0008278543, -0.028720563, -0.0012735784, 2.3441089e-05, -0.01062601, 0.008379541, -0.0015214612, -0.0055332747, -0.0070934403, -0.00060862146, 0.02078942, 0.0064525553, 0.009870991, -0.00013142357, -0.003112285, 0.006960667, -0.0069776443, -0.006353742, 0.048985124, 0.022229394, 0.0020481911, 0.0025878472, 0.010559392, -0.020480802, -0.005852886, -0.011287413, 0.00064725825, -0.00603929, 0.018150775, -0.0008292421, -0.0083348425, -0.0045380737, -0.017026605, 0.002606882, 0.0058194124, 0.006619496, -0.021669615, -0.030633084, -0.0060475697, 0.011555104, 0.0073636803, -0.0024629708, 0.017419899, 0.00822306, -0.017068356, 0.014491975, -0.0040609622, 0.0010485862, 0.015081108, -0.013831337, -0.0037593162, 0.00642672, -0.0014539988, 0.009070959, -0.02439166, 0.01683159, -0.008518713, 0.002486453, 0.009195376, 0.00010449989, 0.020904344, -0.0017218936, -0.0073614838, 0.0007642071, -0.003188146, 0.0094725685, -0.016739603, -0.008743882, 0.014079124, 0.005561303, -0.00022093293, -0.01108631, -0.023708196, -0.007033278, 0.001734533, 0.03486085, -0.002036109, -0.0060884296, 0.0012405657, 0.01779748, 0.017521663, -0.012594627, -0.0011964155, -0.011570083, -0.01019783, -0.0034622506, 0.004613631, -0.015188658, 0.018706964, 0.012864289, -0.003762119, 0.0029768231, 0.0013675981, -0.0026034913, 0.0042949095, 0.010871661, -0.0136412075, 4.1787167e-05, 0.0063394997, 0.0008757451, 0.0034640091, 0.023948975, -0.0004365469, -0.0043057622, -0.01456957, -0.018479085, -0.013150577, -0.0044398396, -0.009070105, -0.0130057745, 0.02223789, -0.01494952, 0.009507944, -0.024255065, 0.012944835, -0.010642314, 0.006109845, 0.004504369, 0.005953853, 0.014099641, 0.025324667, -0.006602372, 0.009921052, 0.0042471495, 0.007022958, -0.011089475, 0.002216266, 0.0068774438, -0.007276129, 0.008886808, -0.0036309473, -0.008535068, -0.0041903243, -0.025768803, 0.002134111, 0.0014105838, 0.0032357734, -0.0014272134, 0.011798383, -0.014881311, -0.016250886, -0.026693972, 0.004307152, -0.0015694808, 0.011026147, -0.018810024, 0.0071239504, -0.010738071, 0.0132130515, 0.0068262285, 0.009747841, -0.0081426, -0.0017391536, -0.0033782062, -0.0052649914, -0.009997463, -0.015021934, -0.003686603, 0.005519439, 0.011117988, 0.019735139, -0.020108217, -0.009389129, -0.0052467897, -0.009509783, 0.0060023656, 0.00024565437, 0.0036544173, -0.024672702, 2.4406467e-05, -0.02322651, -0.0035820315, -0.0025604905, -0.005317863, -0.0040868255, -0.010634936, 0.009138613, -0.0062110173, -0.0034267916, -0.07395892, 0.0063518, 0.011621932, 0.005721578, 0.0018073019, -0.014379611, -0.02073384, -0.0015996096, 0.008201852, -0.008759303, 0.0038643081, -0.008464195, -0.0044734366, 0.007513959, -0.004397051, 0.004067635, -0.012281556, 0.0150062395, 0.0020341028, -0.009534266, -0.017806387, -0.008164217, -0.0031053955, -0.0128218755, -0.007871203, -0.008052797, 0.0003441274, 0.0006940507, 0.0022362561, 0.002647188, 0.012575579, -0.017896766, -0.0046361517, -0.0030249436, 0.005293004, 0.010485339, -0.0028734182, -0.0031815683, 0.016658137, 0.0011841567, 0.0252535, -0.008254083, -0.0015897873, 0.0038236508, 0.012611646, -0.0010006418, 0.00073937175, 0.0018447088, 0.0023391938, 0.009504399, 0.0054556797, 0.010300601, -0.0048193564, 0.024518225, 0.012189084, -0.025815384, 0.006708932, 0.005963363, -0.00110706, -0.002287251, 0.00057652424, 0.021413172, 0.0055792923, -0.0034469077, 0.006248319, -0.006822528, 0.010335451, -0.001488354, -0.007853731, -0.0014373888, 0.004982822, -0.008211345, 0.009575401, -0.020254906, -0.013588853, 0.0030243825, 0.016264424, 0.006468408, -0.0007324734, -0.0007180782, 0.009625549, 0.016635174, 0.0019989724, -0.0009408258, -0.0019726749, 0.013318879, 0.0030436832, -0.005284807, -0.012364606, -0.0103289895, -0.009731246, -0.002398201, 0.0052658278, 0.004732879, -0.011121415, -0.0094813015, -0.029350005, -0.0055312905, -0.007244785, 0.007931169, -0.029064097, 0.0012324562, -0.003951481, 0.0006548486, -0.0130375875, -0.0045213164, 0.0015122737, -0.016291657, 0.0066262307, -0.0050321566, 0.0055250293, 0.0048365775, 0.00013866503, 0.00019886895, -0.0041401903, -0.018996086, 0.00238082, -0.01928341, -0.001297326, -0.008911822, -0.008146457, 0.027545707, -0.006182558, 0.013624976, 0.02296248, 0.0135336, -0.0042758225, -0.0005324491, 0.010478716, -0.01770749, 0.0106557105, 0.0050095352, -0.006026052, -0.018794907, 0.007461543, 0.003354862, 0.009247175, -0.0047753174, 0.0020871924, 0.0008255581, 0.015362993, -0.014844835, 0.00050245685, 0.002148542, -0.015071151, 0.016265053, -0.0022301464, -0.0038964318, 0.0041805804, 0.009737394, 0.011951562, 0.0014801195, 0.006256956, 0.012841568, -0.00133563, 0.0021663536, -0.00983234, 0.0028135006, 0.008049154, -0.017674685, 0.0345473, -0.008542781, 0.016666798, -0.0017108986, -0.004928735, -0.001821239, -0.016229877, -0.007896547, -0.0063523245, -0.003497378, -0.0034359992, 0.009510356, 0.003069736, 0.008194425, -2.1057378e-05, 0.018475827, 0.010116706, -0.0024118156, -0.008483967, 0.0032815405, -0.00018031785, -0.0066303657, 0.006713607, 0.0074971444, 0.0039293696, -0.0058295256, -0.009714898, 0.0015745217, -0.0033145614, -0.0018640084, 0.0025920267, -0.009980614, 0.0059239073, 7.379408e-05, 0.0042645643, 0.012387179, 0.003225773, -0.004676769, 0.0116976965, -0.0036261103, -0.011236806, -0.0034208503, 0.0148291085, -0.013687802, 0.016700428, -0.100046985, 0.013339687, 0.00044227843, -0.0060780174, 0.003660116, -0.0072744447, 0.010466027, -0.008026613, -0.011572751, 0.01559893, -0.011170094, 0.012797739, 0.011654821, -0.029191488, 0.00036970986, 0.0030745722, -0.0027209457, 0.017918367, -0.0048025195, 0.0030944857, 0.0049384506, 0.015710149, -0.022418736, 0.0010696696, 0.0018820273, -0

In [ ]:
def embed_text(text: str) -> np.ndarray:
    resp = genai.embed_content(
        model="gemini-embedding-001",
        content=text,
        task_type=task_type,   # "retrieval_query" or "retrieval_document"
    )
    return np.asarray(resp["embedding"], dtype=np.float32)

In [ ]:
df['Embeddings'] = df['Text'].apply(embed_text)
df

,Title,Text,Embeddings
0,Політика Онбордингу_Офбордингу.pdf,🚀 Політика Онбордингу (Onboarding Poli...,"[-0.0010583504, 0.013385704, 0.02906294, -0.04..."
1,Відпустки та Sick Leaves.pdf,🌴 Політика відпусток та Sick Leaves ...,"[-0.002800844, 0.014772894, 0.020471087, -0.04..."
2,Політика відряджень (Travel Policy).pdf,✈ Політика відряджень (Travel Policy) ...,"[-0.004454881, 0.022114435, 0.026655322, -0.04..."
3,Медичне страхування та Бенефіти.pdf,🩺 Медичне страхування та Бенефіти Ми...,"[-0.00084413256, 0.015962642, 0.02079831, -0.0..."

In [ ]:
def query_similarity_score(query,vector):
    # query --> 'How can I take a sick leave?' TEXT STR
    # vector --> our existing Array (list)

    # Query STR --> LIST
    query_embedding = embed_text(query)

    #SIMILARITY
    return np.dot(query_embedding,vector)

In [ ]:
query = "Скільки в мене на рік доступно вихідних?"
df['Similarity'] = df['Embeddings'].apply(lambda vector: query_similarity_score(query,vector))

In [ ]:
df

,Title,Text,Embeddings,Similarity
0,Політика Онбордингу_Офбордингу.pdf,🚀 Політика Онбордингу (Onboarding Poli...,"[-0.0010583504, 0.013385704, 0.02906294, -0.04...",0.747025
1,Відпустки та Sick Leaves.pdf,🌴 Політика відпусток та Sick Leaves ...,"[-0.002800844, 0.014772894, 0.020471087, -0.04...",0.796225
2,Політика відряджень (Travel Policy).pdf,✈ Політика відряджень (Travel Policy) ...,"[-0.004454881, 0.022114435, 0.026655322, -0.04...",0.738191
3,Медичне страхування та Бенефіти.pdf,🩺 Медичне страхування та Бенефіти Ми...,"[-0.00084413256, 0.015962642, 0.02079831, -0.0...",0.745714

In [ ]:
#now let`s extract `the text we need to have as context to answer our question
df.sort_values('Similarity',ascending=False)
df.sort_values('Similarity',ascending=False)[['Title','Text']]
df.sort_values('Similarity',ascending=False)[['Title','Text']].iloc[0]

Title                         Відпустки та Sick Leaves.pdf
Text     🌴   Політика   відпусток   та   Sick   Leaves ...
Name: 1, dtype: object

In [ ]:
def  most_similar_doc(query):
    df['Similarity'] = df['Embeddings'].apply(lambda vector: query_similarity_score(query,vector))
    title = df.sort_values('Similarity',ascending=False)[['Title','Text']].iloc[0]['Title']
    text = df.sort_values('Similarity',ascending=False)[['Title','Text']].iloc[0]['Text']
    return title,text

In [ ]:
title, text = most_similar_doc('Хочу відвідати конференцію. Чи може компанія мені це покрити?')
print(title,text)

Політика відряджень (Travel Policy).pdf ✈   Політика   відряджень   (Travel   Policy)   Цей   документ   регулює   всі   робочі   поїздки,   що   здійснюються   від   імені   компанії,   включаючи   конференції,   зустрічі   з   клієнтами   та   внутрішні   воркшопи.   1.   Планування   та   Апрув   (Approval)   1.1.   Запит   на   поїздку   ●   Кожне   відрядження   має   бути   погоджене   з   лінійним   менеджером   принаймні   за   14   днів   (для   внутрішніх   поїздок)   або   за   30   днів   (для   міжнародних).   ●   Запит   подається   через   систему   (наприклад,   Slack,   Jira   або   ERP)   і   повинен   містити:   мету   поїздки,   дати,   орієнтовний   бюджет.   1.2.   Бронювання   ●   Авіа/Залізничні   квитки:   Компанія   оплачує   квитки   класу   «Економ».   Квитки   «Бізнес-класу»   потребують   окремого   погодження   СЕО.   ●   Готелі:   Стандарт   проживання   —   готель   не   нижче   3*   або   апартаменти   (Airbnb),   що   знаходяться   в   безпечному   районі   з   доступом   до   Wi-Fi.     2.   Витрати   та   Ліміти   (Daily   Allowance)   2.1.   Добові   (Per   Diem)   Добові   покривають   харчування   та   дрібні   особисті   витрати.   Компанія   встановлює   наступні   ліміти   (приклад):   ●   В   межах   країни:   $[Сума]$   на   добу.   ●   За   кордоном:   $[Сума]$   на   добу   (залежно   від   країни   призначення   згідно   з   внутрішньою   сіткою).   ●   Примітка:   Якщо   сніданок   включено   у   вартість   готелю   або   обід   оплачено   клієнтом,   добові   не   зменшуються   (або   зменшуються   на   20%,   оберіть   свій   варіант).   2.2.   Транспортні   витрати   ●   Таксі:   Компанія   компенсує   таксі   до/з   аеропорту/вокзалу   та   між   локаціями   ділових   зустрічей.   Рекомендується   використовувати   корпоративні   акаунти   (наприклад,   Uber   for   Business).   ●   Оренда   авто:   Дозволяється   лише   за   умови,   що   це   дешевше   за   таксі   або   необхідно   для   специфіки   роботи.     3.   Процес   компенсації   (Reimbursement)   3.1.   Звітність  ●   Протягом   5   робочих   днів   після   повернення   співробітник   має   подати   звіт   про   витрати.   ●   Чеки:   Всі   витрати   (крім   фіксованих   добових)   мають   бути   підтверджені   фіскальними   чеками   або   інвойсами.   Фото   чеків   завантажуються   в   систему   звітності.   3.2.   Виплата   ●   Компенсація   витрат,   здійснених   власними   коштами,   відбувається   протягом   7-10   робочих   днів   після   затвердження   звіту.   ●   За   запитом   компанія   може   видати   аванс   на   картку   за   3   дні   до   поїздки.     4.   Безпека   та   Здоров'я   ●   Страхування:   Для   закордонних   поїздок   компанія   обов'язково   оформлює   медичну   страховку   на   весь   період   подорожі.   ●   Форс-мажор:   У   разі   скасування   рейсу   або   хвороби   під   час   поїздки,   співробітник   повинен   негайно   зв'язатися   з   менеджером   або   HR   для   координації   дій.     5.   Bleisure   (Business   +   Leisure)   Компанія   не   заперечує,   якщо   співробітник   бажає   залишитися   в   місті   відрядження   на   вихідні   за   власний   рахунок.   У   такому   разі:   ●   Компанія   оплачує   квитки   в   обидва   боки   (якщо   ціна   не   змінюється   через   зміну   дати).   ●   Співробітник   самостійно   оплачує   готель   та   харчування   за   додаткові   дні.

## Етап 3: Генерація відповіді

In [ ]:
def rag_implement(query):
    #Retrival Document
    title,text = most_similar_doc(query)
    #AG - Model
    model = genai.GenerativeModel('gemini-2.5-flash')
    #Augment --> prompt engineering
    prompt = f'Answer this query:\n{query}. \n Only use this context to answer: \n{text}'
    #Sourcing(title) - what doc was used
    response = model.generate_content(prompt)
    # return f'{response.text}\n\n Source Doc Title: {title}'
    return response.text,title

In [ ]:
print(rag_implement('А чи є курси французької?'))

('У наданому контексті немає інформації щодо наявності курсів французької мови. Текст описує лише політику онбордингу та офбордингу.', 'Політика Онбордингу_Офбордингу.pdf')

## Chunking

In [ ]:
#Simple chunking
def text_splitter(text, chunk_size=500, overlap=50):
    chunks = []
    # Ensure text is a string
    if not isinstance(text, str):
        text = str(text)

    start = 0
    while start < len(text):
        end = start + chunk_size
        chunk = text[start:end]
        chunks.append(chunk)
        start += (chunk_size - overlap)
    return chunks

In [ ]:
# Create a list to store the chunked data
chunked_data = []

for index, row in df.iterrows():
    title = row['Title']
    full_text = row['Text']

    # Split the full text into chunks
    chunks = text_splitter(full_text)

    for chunk in chunks:
        chunk_embedding = embed_text(chunk)
        chunked_data.append({'Title': title, 'Text': chunk, 'Embeddings': chunk_embedding})

In [ ]:
# Create a new DataFrame from the chunked data
df_chunks = pd.DataFrame(chunked_data)

display(df_chunks.head())

,Title,Text,Embeddings
0,Політика Онбордингу_Офбордингу.pdf,🚀 Політика Онбордингу (Onboarding Poli...,"[-0.0012144527, 0.01709069, 0.027740538, -0.04..."
1,Політика Онбордингу_Офбордингу.pdf,план на перший день. ● Робоче мі...,"[0.0052686357, 0.0008702208, 0.016166795, -0.0..."
2,Політика Онбордингу_Офбордингу.pdf,допомагає з побутовими питаннями (д...,"[-0.00999991, 0.014663069, 0.022911422, -0.038..."
3,Політика Онбордингу_Офбордингу.pdf,● Тиждень 1: Чітке визначення очіку...,"[-0.01713143, 0.012525202, 0.024632894, -0.048..."
4,Політика Онбордингу_Офбордингу.pdf,"фесійним, прозорим та етичним, незалеж...","[-0.010839325, 0.003092978, 0.016381774, -0.04..."

In [ ]:
df_chunks = df_chunks.reset_index(drop=True)

df_chunks["Embeddings"] = df_chunks["Embeddings"].apply(lambda x: np.asarray(x, dtype=np.float32))

EMB_MATRIX = np.vstack(df_chunks["Embeddings"].to_numpy())
EMB_MATRIX_N = EMB_MATRIX / (np.linalg.norm(EMB_MATRIX, axis=1, keepdims=True) + 1e-12)

Get the most relevant chunks to the query

In [ ]:
def get_relevant_chunks(query: str, num_chunks: int = 3):
    q = np.asarray(embed_text(query), dtype=np.float32)   # one API call
    sims = EMB_MATRIX @ q                                 # dot product vs all chunks
    top_idx = np.argsort(-sims)[:num_chunks]
    top = df_chunks.iloc[top_idx]
    return top["Text"].tolist(), top["Title"].tolist()

In [ ]:
get_relevant_chunks("Скільки в мене на рік доступно вихідних?")

(['🌴   Політика   відпусток   та   Sick   Leaves   1.   Оплачувана   щорічна   відпустка   (Paid   Time   Off   -   PTO)   1.1.   Нарахування   та   ліміти   ●   Кількість   днів:   Кожен   співробітник   має   право   на   24   робочих   дні   оплачуваної   відпустки   на   рік.   ●   Період   нарахування:   Відпустка   нараховується   пропорційно   відпрацьованому   часу,   1.67   дня   за   кожен   повний   місяць   роботи.   ●   Початок   використання:   Співробітник   може   брати   першу   ві',
  ')   Періоди,   коли   відпустки   обмежені   через   високе   навантаження   (наприклад,   перед   релізом   продукту   або   в   кінці   фінансового   року).   ●   Перенесення   залишків   (Carry-over):   На   кінець   календарного   року   співробітник   може   перенести   не   більше   5   днів   на   наступний   рік.   Ці   дні   мають   бути   використані   до   кінця   першого   кварталу   (31   березня).     2.   Лікарняні   (Sick   Leaves)   2.1.   Короткотермінові   лікарняні   (Self-ce',
  '  3-5   робочих   днів   (додатково   до   державної   відпустки).   ●   Втрата   близької   людини   (Bereavement   leave):   3-5   робочих   днів.   3.3.   Державні   свята   Компанія   дотримується   офіційного   календаря   державних   свят   країни,   де   зареєстрований   співробітник.   Якщо   робота   у   святковий   день   є   критичною,   вона   компенсується   подвійною   оплатою   або   додатковим   вихідним   (Day   off).     4.   Як   подати   запит?   1.   Узгодьте   дати   усно  '],
 ['Відпустки та Sick Leaves.pdf',
  'Відпустки та Sick Leaves.pdf',
  'Відпустки та Sick Leaves.pdf'])

## Improving chunking - by split per sentence + adding preprocessing

In [ ]:
import nltk
import re
from nltk.tokenize import sent_tokenize

In [ ]:
nltk.download('punkt')
nltk.download('punkt_tab')

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt.zip.
[nltk_data] Downloading package punkt_tab to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt_tab.zip.

True

In [ ]:
def text_splitter(text, chunk_size=500, overlap=50):
    chunks = []
    # Ensure text is a string
    if not isinstance(text, str):
        text = str(text)

    # Preprocessing: remove extra whitespace and unnecessary symbols
    # Replace multiple spaces/newlines with a single space.
    text = re.sub(r'[\s]+', ' ', text)
    # Keep alphanumeric characters, spaces, and common punctuation.
    # Added Cyrillic character range (а-яА-Я) for Ukrainian text.
    text = re.sub(r'[^a-zA-Zа-яА-ЯІіЇїЄє0-9\s.,!?;:]', '', text)
    text = text.strip()

    sentences = sent_tokenize(text)

    current_sentence_index = 0
    while current_sentence_index < len(sentences):
        current_chunk_sentences = []
        current_chunk_length = 0

        # Add sentences from the end of the previous chunk for overlap
        if len(chunks) > 0:
            last_chunk_sentences = sent_tokenize(chunks[-1])
            temp_overlap_chars = 0
            overlap_sentences_for_this_chunk = []

            # Iterate backwards in the previous chunk's sentences to find enough for overlap
            for i in range(len(last_chunk_sentences) - 1, -1, -1):
                sentence = last_chunk_sentences[i]
                # Add 1 for the space that will be between sentences when joined
                if temp_overlap_chars + len(sentence) + (1 if temp_overlap_chars > 0 else 0) <= overlap:
                    overlap_sentences_for_this_chunk.insert(0, sentence) # Add to front to maintain order
                    temp_overlap_chars += len(sentence) + (1 if temp_overlap_chars > 0 else 0)
                else:
                    break
            current_chunk_sentences.extend(overlap_sentences_for_this_chunk)
            current_chunk_length = len(" ".join(current_chunk_sentences)) if current_chunk_sentences else 0

        # Now add new sentences from the `sentences` list until chunk_size is met
        temp_sentence_idx = current_sentence_index
        while temp_sentence_idx < len(sentences):
            sentence = sentences[temp_sentence_idx]
            # Check if adding this sentence will exceed chunk_size
            # Add 1 for the space that will be between sentences when joined
            if current_chunk_length + len(sentence) + (1 if current_chunk_sentences else 0) <= chunk_size:
                current_chunk_sentences.append(sentence)
                current_chunk_length += len(sentence) + (1 if current_chunk_sentences else 0)
                temp_sentence_idx += 1
            else:
                break # Current chunk is full enough

        # Handle cases where a single sentence is larger than chunk_size, or if no sentences were added
        if not current_chunk_sentences and current_sentence_index < len(sentences):
            # If the current_chunk_sentences is empty, it means the very first sentence is too long or no sentences were processed yet
            # Take the current sentence, even if it's too long, as a single chunk
            current_chunk_sentences.append(sentences[current_sentence_index])
            temp_sentence_idx = current_sentence_index + 1 # Advance pointer

        if current_chunk_sentences:
            chunks.append(" ".join(current_chunk_sentences))

        current_sentence_index = temp_sentence_idx # Move to the point where the next chunk should start

    return chunks

In [ ]:
chunked_data = []

for index, row in df.iterrows():
    title = row['Title']
    full_text = row['Text']

    # Split the full text into chunks
    chunks = text_splitter(full_text)

    # For each chunk, create a new entry with title, chunk text, and embedding
    for chunk in chunks:
        chunk_embedding = embed_text(chunk)
        chunked_data.append({'Title': title, 'Text': chunk, 'Embeddings': chunk_embedding})

# Create a new DataFrame from the chunked data
df_chunks = pd.DataFrame(chunked_data)

display(df_chunks.head())

,Title,Text,Embeddings
0,Політика Онбордингу_Офбордингу.pdf,Політика Онбордингу Onboarding Policy Мета онб...,"[-0.00033089292, 0.01798767, 0.023416419, -0.0..."
1,Політика Онбордингу_Офбордингу.pdf,Welcome Box: Новачок отримує мерч компанії худ...,"[-0.012382606, 0.010289543, 0.01969329, -0.048..."
2,Політика Онбордингу_Офбордингу.pdf,Протягом цього часу проводяться регулярні зуст...,"[-0.025169095, 0.010689628, 0.018843293, -0.05..."
3,Політика Онбордингу_Офбордингу.pdf,1. Повідомлення про звільнення Notice Period ...,"[-0.010585628, 0.0041336445, 0.014146942, -0.0..."
4,Політика Онбордингу_Офбордингу.pdf,3. Повернення майна та доступів Техніка: Пове...,"[-0.00687672, 0.008383752, 0.01061246, -0.0471..."

In [ ]:
df_chunks = df_chunks.reset_index(drop=True)

df_chunks["Embeddings"] = df_chunks["Embeddings"].apply(lambda x: np.asarray(x, dtype=np.float32))

EMB_MATRIX = np.vstack(df_chunks["Embeddings"].to_numpy())
EMB_MATRIX_N = EMB_MATRIX / (np.linalg.norm(EMB_MATRIX, axis=1, keepdims=True) + 1e-12)

In [ ]:
get_relevant_chunks("Скільки в мене на рік доступно вихідних?")

(['Політика відпусток та Sick Leaves 1. Оплачувана щорічна відпустка Paid Time Off  PTO 1.1. Нарахування та ліміти  Кількість днів: Кожен співробітник має право на 24 робочих дні оплачуваної відпустки на рік. Період нарахування: Відпустка нараховується пропорційно відпрацьованому часу, 1.67 дня за кожен повний місяць роботи. Початок використання: Співробітник може брати першу відпустку після проходження випробувального терміну зазвичай 3 місяці, якщо інше не узгоджено з менеджером. 1.2.',
  '1.2. Правила планування  Попереднє сповіщення: Про відпустку тривалістю понад 3 дні необхідно повідомити за 2 тижні . Для тривалих відпусток понад 10 днів  за 1 місяць . Blackout dates: Опціонально Періоди, коли відпустки обмежені через високе навантаження наприклад, перед релізом продукту або в кінці фінансового року. Перенесення залишків Carryover: На кінець календарного року співробітник може перенести не більше 5 днів на наступний рік.',
  'Рішення приймається індивідуально менеджером та HR відділом залежно від ситуації та навантаження команди. 3.2. Соціальні відпустки Paid Компанія надає додаткові оплачувані вихідні у наступних випадках:  Весілля співробітника: 3 робочі дні. Народження дитини для батька: 35 робочих днів додатково до державної відпустки. Втрата близької людини Bereavement leave: 35 робочих днів. 3.3. Державні свята Компанія дотримується офіційного календаря державних свят країни, де зареєстрований співробітник.'],
 ['Відпустки та Sick Leaves.pdf',
  'Відпустки та Sick Leaves.pdf',
  'Відпустки та Sick Leaves.pdf'])

In [ ]:
def rag_implement_chunked(query):
    # Retrieval of relevant chunks
    relevant_texts, source_titles = get_relevant_chunks(query, num_chunks=3)

    # Concatenate relevant texts for the prompt
    context = " ".join(relevant_texts)

    # AG - Model
    model = genai.GenerativeModel('gemini-2.5-flash')

    # Augment --> prompt engineering
    prompt = f'Answer this query:\n{query}. \n Only use this context to answer: \n{context}'

    response = model.generate_content(prompt)

    # Sourcing (titles of documents from which chunks were taken)
    # Get unique titles from the documents that contributed the relevant chunks
    source_titles = df_chunks[df_chunks['Text'].isin(relevant_texts)]['Title'].unique().tolist()

    return response.text, "\n".join(sorted(set(source_titles)))

In [ ]:
rag_implement_chunked("Скільки в мене на рік доступно вихідних?")

('Згідно з наданим контекстом, кожен співробітник має право на 24 робочих дні оплачуваної відпустки на рік.',
 'Відпустки та Sick Leaves.pdf')

## Extending the user query

In [ ]:
def extend_query(original_query):
    model = genai.GenerativeModel('gemini-2.5-flash')
    prompt = f"""Given the query: '{original_query}', generate 2-3 alternative ways to phrase this question that could be used to find similar information.
    Return each variant on a new line and include the original query as one of the options.
    Do not include any commentary, introductory or concluding text, just the list of queries.
    The result must be in the language of the original query, no translations. If it`s in English, return variants in English, if in Ukrainian, return in Ukrainian, etc."""
    response = model.generate_content(prompt)
    extended_queries = [q.strip() for q in response.text.split('\n') if q.strip()]
    if original_query not in extended_queries:
        extended_queries.insert(0, original_query) # Ensure original query is always included
    return extended_queries

In [ ]:
extend_query("Чи є курси французької?")

['Чи є курси французької?',
 'Де можна вивчати французьку мову?',
 'Чи проводяться заняття з французької мови?']

In [ ]:
def rag_implement_chunked_extended(query):
    # Extend the query
    extended_queries = extend_query(query)

    # Retrieve relevant chunks for each extended query
    all_relevant_texts = []
    for ext_query in extended_queries:
        all_relevant_texts.extend(get_relevant_chunks(ext_query, num_chunks=2)) # Get 1 chunk per extended query
    combined_context_chunks = []
    for ext_query in extended_queries:
        combined_context_chunks.extend(get_relevant_chunks(ext_query, num_chunks=1))

    # Remove duplicates while preserving order
    # Convert to set and back to list, or iterate and add if not already present
    seen_chunks = set()
    unique_combined_context_chunks = []
    for chunk_text in combined_context_chunks:
        if chunk_text not in seen_chunks:
            unique_combined_context_chunks.append(chunk_text)
            seen_chunks.add(chunk_text)

    # Limit the number of chunks passed to the LLM to avoid token limits
    final_relevant_texts = unique_combined_context_chunks[:3] # Using up to 3 unique chunks

    context = " ".join(final_relevant_texts)

    model = genai.GenerativeModel('gemini-2.5-flash')
    prompt = f'Answer this query:\n{query}. \n Only use this context to answer: \n{context}'

    response = model.generate_content(prompt)

    source_titles = []
    for chunk_text in final_relevant_texts:
        titles_for_chunk = df_chunks[df_chunks['Text'] == chunk_text]['Title'].unique().tolist()
        source_titles.extend(titles_for_chunk)
    source_titles = list(set(source_titles)) # Get unique titles

    return response.text, source_titles

In [ ]:
def rag_implement_chunked_extended(query: str):
    extended_queries = extend_query(query)

    combined_context_chunks = []
    source_titles = []

    # get 1 top chunk per extended query
    for ext_query in extended_queries:
        texts, titles = get_relevant_chunks(ext_query, num_chunks=1)  # unpack
        combined_context_chunks.extend(texts)
        source_titles.extend(titles)

    # remove duplicate chunks while preserving order
    seen = set()
    unique_chunks = []
    for t in combined_context_chunks:
        if t not in seen:
            unique_chunks.append(t)
            seen.add(t)

    final_relevant_texts = unique_chunks[:3]
    context = " ".join(final_relevant_texts)

    model = genai.GenerativeModel("gemini-2.5-flash")
    prompt = f"Answer this query:\n{query}\nOnly use this context to answer:\n{context}"
    response = model.generate_content(prompt)

    used_titles = df_chunks[df_chunks["Text"].isin(final_relevant_texts)]["Title"].unique().tolist()

    return response.text, "\n".join(sorted(set(used_titles)))

In [ ]:
rag_implement_chunked_extended("Чи є курси французької?")

('Згідно з наданим контекстом, компанія організує групові заняття з **англійської** мови. Про курси французької мови не згадується.',
 'Медичне страхування та Бенефіти.pdf')

In [ ]:
import gradio as gr

description = "Welcome to HR policies bureau. Here you can ask anything about onboarding process, medical insuranse, leave policies and benefits."
title = "HR Wiki 👾"
output1 = gr.Textbox(label="Answer")
output2 = gr.Textbox(label="Where it comes from?")
gr.Interface(fn=rag_implement_chunked,
             title=title,
             description=description,
             inputs=["text"],
             outputs=[output1,output2]).launch(debug=True)

It looks like you are running Gradio on a hosted Jupyter notebook, which requires `share=True`. Automatically setting `share=True` (you can turn this off by setting `share=False` in `launch()` explicitly).

Colab notebook detected. This cell will run indefinitely so that you can see errors and logs. To turn off, set debug=False in launch().
* Running on public URL: https://0c57171230d48c8d60.gradio.live

This share link expires in 1 week. For free permanent hosting and GPU upgrades, run `gradio deploy` from the terminal in the working directory to deploy to Hugging Face Spaces (https://huggingface.co/spaces)

Keyboard interruption in main thread... closing server.
Killing tunnel 127.0.0.1:7860 <> https://0c57171230d48c8d60.gradio.live